In [1]:
matrix = [[1,2,3],[4,5,6]]

In [2]:
matrix

[[1, 2, 3], [4, 5, 6]]

In [3]:
import numpy as np

In [4]:
matrix = np.array(matrix)

matrix

In [5]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
type(matrix)

numpy.ndarray

In [7]:
matrix.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [8]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
matrix(0)

TypeError: 'numpy.ndarray' object is not callable

In [10]:
matrix[0]

array([1, 2, 3])

In [11]:
matrix[0,0]

1

In [12]:
matrix[0][0]

1

In [14]:
np.append([7,8,9],matrix)

array([7, 8, 9, 1, 2, 3, 4, 5, 6])

In [15]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
matrix = np.append(matrix,[7,8,9])

In [30]:
matrix.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
matrix = np.insert([10,11,12],obj=0,values=matrix)

In [51]:
matrix.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
np.delete(arr=matrix,obj=0)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
np.delete(arr=matrix,obj=[9,10,11])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])